
// Campus
export const RECEIVE_CAMPUSES = 'RECEIVE_CAMPUSES';
export const RECEIVE_CAMPUS = 'RECEIVE_CAMPUS';
export const DELETE_CAMPUS = 'DELETE_CAMPUS';
export const NEW_CAMPUS = 'NEW_CAMPUS';

// Users
export const RECEIVE_STUDENTS = 'RECEIVE_STUDENTS';
export const RECEIVE_STUDENT = 'RECEIVE_STUDENT';
export const DELETE_STUDENT = 'RECEIVE_STUDENT';
export const NEW_STUDENT = 'NEW_STUDENT';
